In [1]:
import  numpy

In [25]:
arr=numpy.array([1,2,3,4,5])

In [24]:
print([arr])

[array(['apple', 'eye', 'banana', 'kidney', 'stone'], dtype='<U6')]


In [4]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [6]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr)
print(arr)





[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [8]:
arr=np.array([1,2,3,4])
print(arr[2])

3


In [9]:
print(arr[2]+arr[3])

7


In [10]:
arr=np.array([5,12,18,25])
print(arr[0]+arr[1])

17


In [21]:
print(arr[0:1])

['apple']


In [13]:
print(arr[1:3])

[12 18]


In [14]:
print(arr[0:])

[ 5 12 18 25]


In [17]:
arr=np.array([1,8,9,7,5,6,7,4,2,8,2])
print(arr[1::3])

[8 5 4 2]


In [18]:
print(arr.dtype)

int32


In [20]:
arr=np.array(['apple','eye','banana','kidney','stone'])
print(arr.dtype)

<U6


In [26]:
arr[0]=42
print(arr)

[42  2  3  4  5]


In [39]:
arr=np.array([5,6,7,9,6,7,5,6,8,5,8,71])
new_arr=arr.reshape(2,3,2)
print(new_arr)


[[[ 5  6]
  [ 7  9]
  [ 6  7]]

 [[ 5  6]
  [ 8  5]
  [ 8 71]]]
