In [1]:
import numpy as np

In [3]:
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


In [4]:
multi_array = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])
print(multi_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(array[0])

1


In [8]:
zero = np.zeros(5)
one = np.ones(5)
print(zero, one)

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.]


In [9]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [17]:
np.linspace(0, 100, num=10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [21]:
x = np.ones(5, dtype=np.int64)
y = np.ones(5, dtype=np.float64)
print(x, y)

[1 1 1 1 1] [1. 1. 1. 1. 1.]


In [26]:
array2 = np.array([2, 10, 1, 5, 4, 6, 3, 7, 9, 8])
print(array2)

[ 2 10  1  5  4  6  3  7  9  8]


In [27]:
np.sort(array2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
back = np.append(array2, 3)
front = np.append(3, array2)
print(front, back)

[ 3  2 10  1  5  4  6  3  7  9  8] [ 2 10  1  5  4  6  3  7  9  8  3]


In [33]:
np.delete(array2, [2])

array([ 2, 10,  5,  4,  6,  3,  7,  9,  8])

In [35]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
np.concatenate((arr1, arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
p = np.array([[1, 2, 3], [4, 5, 6]])
q = np.array([[7, 8, 9]])
np.concatenate((p, q), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
shape = np.array([
    [[1, 2, 3],
    [4, 5, 6]],
    
    [[7, 8, 9],
    [10, 11, 12]],
    
    [[13, 14, 15],
    [16, 17, 18]]
])

In [44]:
shape.ndim

3

In [45]:
shape.size

18

In [46]:
shape.shape

(3, 2, 3)

In [51]:
random = np.arange(10)
print(random)

[0 1 2 3 4 5 6 7 8 9]


In [58]:
# reshape(row, column) where row and column must be multiply of size of the array that is getting reshaped
reshape = random.reshape(5, 2)
print(reshape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [60]:
np.reshape(random, newshape=(2, 5), order='C') # order parameter is optional 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
single = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
single.shape

(10,)

In [65]:
row_vector = single[np.newaxis, :]
column_vector = single[:, np.newaxis]
print(row_vector.shape, 
column_vector.shape)

(1, 10) (10, 1)


In [66]:
data = np.array([100, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90])

In [67]:
data[5]

95

In [68]:
data[0:2]

array([100,  99])

In [69]:
data[7:]

array([93, 92, 91, 90])

In [70]:
data[:9]

array([100,  99,  98,  97,  96,  95,  94,  93,  92])

In [71]:
data[-4:-9]

array([], dtype=int32)

In [72]:
data[-4:-1]

array([93, 92, 91])

In [73]:
new = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [77]:
print(new[new <= 6])

[1 2 3 4 5 6]


In [78]:
con = new[new % 2 == 0]
print(con)

[ 2  4  6  8 10 12]


In [80]:
no = np.nonzero(new <10)
no

(array([0, 0, 0, 0, 1, 1, 1, 1, 2], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0], dtype=int64))

In [81]:
data1 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
data2 = np.array([
    [[99, 98, 97], [96, 95,94]],
    [[93, 92, 91], [90, 89, 88]]
])
data1 + data2

array([[[100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100]]])

In [82]:
data2 - data1

array([[[98, 96, 94],
        [92, 90, 88]],

       [[86, 84, 82],
        [80, 78, 76]]])

In [83]:
data1 - data2

array([[[-98, -96, -94],
        [-92, -90, -88]],

       [[-86, -84, -82],
        [-80, -78, -76]]])

In [84]:
data1 * data2

array([[[  99,  196,  291],
        [ 384,  475,  564]],

       [[ 651,  736,  819],
        [ 900,  979, 1056]]])

In [93]:
data2 / data1

array([[[99.        , 49.        , 32.33333333],
        [24.        , 19.        , 15.66666667]],

       [[13.28571429, 11.5       , 10.11111111],
        [ 9.        ,  8.09090909,  7.33333333]]])

In [92]:
data1.min()

1

In [91]:
data2.max()

99

In [90]:
data1.sum()

78

In [95]:
np.average(data2)

93.5

In [96]:
np.std(data1)

3.452052529534663

In [97]:
np.product(data2)

-1778720768

In [98]:
np.unique(data1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
data2.T

array([[[99, 93],
        [96, 90]],

       [[98, 92],
        [95, 89]],

       [[97, 91],
        [94, 88]]])

In [104]:
data1.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])